"use client";
import { useEffect, useState } from "react";
import { userManagementService } from "@/services/userManagement.service";
const labels = { customers: "Customers", admins: "Admins", "support-agents": "Support Agents" };
export default function UserManagementPage({ group }) {
  const [users, setUsers] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); setUsers((await userManagementService.getUsers(group, { search, status }))?.users || []); } catch (error) { console.error(error); setUsers([]); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [status]);
  const updateStatus = async (id, nextStatus) => { if (!window.confirm(`Set this account to ${nextStatus}?`)) return; await userManagementService.updateStatus(id, nextStatus); load(); };
  const title = labels[group];
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-white">{title}</h1><p className="text-sm text-slate-400">Manage account details, verification and account status.</p></div><div className="rounded-2xl border border-slate-700 bg-slate-800 p-4 md:p-5"><div className="mb-5 flex flex-col gap-3 md:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === "Enter" && load()} placeholder="Search name, username, email or phone" className="w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-white"/><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-white"><option value="ALL">All Status</option><option value="ACTIVE">Active</option><option value="PENDING">Pending</option><option value="BLOCKED">Blocked</option></select><button onClick={load} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Search</button></div>{loading ? <p className="text-slate-400">Loading {title.toLowerCase()}...</p> : <div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="border-b border-slate-700 text-slate-300"><tr><th className="py-3">Basic Information</th><th>Contact</th><th>Role</th><th>Verification</th><th>Account Status</th><th>Registration Date</th><th className="text-right">Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-slate-700"><td className="py-3 text-white"><div className="font-semibold">{user.name}</div><div className="text-xs text-slate-400">@{user.username}</div></td><td className="text-slate-300"><div>{user.email}</div><div className="text-xs text-slate-400">{user.phone || "-"}</div></td><td>{user.role}</td><td>{user.isEmailVerified ? "VERIFIED" : "UNVERIFIED"}</td><td>{user.status}</td><td className="text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</td><td className="text-right"><button onClick={() => updateStatus(user.id, user.status === "ACTIVE" ? "BLOCKED" : "ACTIVE")} className={`rounded px-3 py-1 text-xs font-semibold text-white ${user.status === "ACTIVE" ? "bg-red-600" : "bg-green-600"}`}>{user.status === "ACTIVE" ? "Block" : "Activate"}</button></td></tr>)}{!users.length && <tr><td colSpan="7" className="py-8 text-center text-slate-400">No {title.toLowerCase()} found.</td></tr>}</tbody></table></div>}</div></div>;
}
