ALTER TYPE "OrderItemStatus"
ADD VALUE IF NOT EXISTS 'DELIVERED';

ALTER TYPE "OrderItemStatus"
ADD VALUE IF NOT EXISTS 'COMPLETED';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'PARTIALLY_DELIVERED';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'PARTIALLY_COMPLETED';

ALTER TYPE "OrderStatus"
ADD VALUE IF NOT EXISTS 'PARTIALLY_CANCELLED';